### ISSUE TITLE
Training step throws an error with empty/small sketches, should report reason and make a suggestion to fix

### ISSUE THREAD

**Issue by Electrocyte** [KoslickiLab/YACHT#12]
As a note before the issue, YACHT works fine using the default settings.

I tried making a sketch using the bacterial operons from refseq (extracted with primer regex sequences) to use YACHT for 16S-23S reads. The reason for this is I am targeting rDNA, not the entire genome. Is this a problem that YACHT can tackle or will the relative number of kmers in the rDNA be too few?

Inputs in the /BAC/ folder include:

NZ_LT992472.1_Staphylococcus_aureus_isolate_16S-ITS-23S_complement.fasta (15,000 genomes)

>NZ_LT992472.1_Staphylococcus_aureus_isolate16S-ITS-23S
AGAGTTTGATCCTGGCTCAGGATGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGAACGGACGAGAAGCTTGCTTCTCTGATGTTAGCGGCGGACGGGTGAGTAACACGTGGATAACCTACCTATAAGACTGGGATAACTTCGGGAAACCGGAGCTAATACCGGATAATATTTTGAACCGCATGGTTCAAAAGTGAAAGACGGTCTTGCTGTCACTTATAGATGGATCCGCGCTGCATTAGCTAGTTGGTAAGGTAACGGCTTACCAAGGCAACGATGCATAGCCGACCTGAGAGGGTGATCGGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTAGGGAATCTTCCGCAATGGGCGAAAGCCTGACGGAGCAACGCCGCGTGAGTGATGAAGGTCTTCGGATCGTAAAACTCTGTTATTAGGGAAGAACATATGTGTAAGTAACTGTGCACATCTTGACGGTACCTAATCAGAAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGCGCGTAGGCGGTTTTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAG...etc

```bash
time sourmash sketch dna -f -p k=31,scaled=1000,abund *.fasta -o BAC-operon-k31.sig.zip
```

I generate the sample sketches (which work fine using the default sketch for gtdb:
```bash
time sourmash sketch dna -f -p k=31,scaled=1000,abund -o BAC-operon-k31.sig.zip my_sample.fastq
```

Then I generate the reference sketches:
```bash
time python make_training_data_from_sketches.py --ref_file 'BAC-operon-k31.sig.zip' --ksize 31 --out_prefix 'BAC_k31_ani_thresh_0.95' --ani_thresh 0.95
```

I am met with the following warning:
```bash
/miniconda3/envs/yacht/lib/python3.10/site-packages/scipy/sparse/_index.py:143: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)
/miniconda3/envs/yacht/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/miniconda3/envs/yacht/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
```

While the yacht_run works with no issues, the output is bizarre:
```bash
########### k31 BAC, coverage = 1, p = 0.99, ani = 0.95
### high concentration 10K CFU / mL
time python run_YACHT.py --ref_matrix 'BAC_k31_ani_thresh_0.95ref_matrix_processed.npz' \
    --sample_file 'sample.sig.zip' \
    --ani_thresh 0.95 --significance 0.99 --min_coverage 1 --ksize 31 \
    --outfile 'my_sample_yacht_results-ani95-p99-k31-BAC.csv'```
```
    
Output looks like this:

```csv
,organism_name,original_index,processed_index,num_unique_kmers_in_genome_sketch,num_total_kmers_in_genome_sketch,genome_scale_factor,num_total_kmers_in_sample_sketch,num_exclusive_kmers_in_sample_sketch,sample_scale_factor,min_coverage,nontrivial_overlap,in_sample_est,p_vals,num_exclusive_kmers,num_exclusive_kmers_coverage,num_matches,acceptance_threshold_wo_coverage,acceptance_threshold_with_coverage,actual_confidence_wo_coverage,actual_confidence_with_coverage,alt_confidence_mut_rate,alt_confidence_mut_rate_with_coverage
7,,12,7,6,6.0,1000,842670.0,54035,1000,1.0,1.0,True,1.0,0,0,0,0.0,0.0,0.0,0.0,-1,-1
13,,23,13,7,7.0,1000,842670.0,54035,1000,1.0,1.0,True,1.0,0,0,0,0.0,0.0,0.0,0.0,-1,-1
14,,24,14,6,6.0,1000,842670.0,54035,1000,1.0,1.0,True,1.0,0,0,0,0.0,0.0,0.0,0.0,-1,-1
17,,30,17,5,5.0,1000,842670.0,54035,1000,1.0,1.0,True,1.0,0,0,0,0.0,0.0,0.0,0.0,-1,-1
18,,32,18,9,9.0,1000,842670.0,54035,1000,1.0,1.0,True,1.0,0,0,0,0.0,0.0,0.0,0.0,-1,-1
25,,40,25,8,8.0,1000,842670.0,54035,1000,1.0,1.0,True,0.5045354668268573,3,3,0,0.0,0.0,0.49546453317314265,0.49546453317314265,0.16796854767978497,0.16796854767978497
```

**Comment by dkoslicki** [comment]
Apologies I overlooked this @Electrocyte ! With such small "genomes" and such a high scale factor, it's not surprising the results look funky: it appears that no exclusive kmers (ones appearing in a single genome) were found. The scale factor indicates what fraction of your data you will be taking (in expectation), so a scale factor of 1000 and an average 16S genome size of ~1-2kbp, you'll basically be getting 1 or 2 k-mers per reference "genome", so not at all surprising that it's unlikely these will be unique to each genome.

I'd suggest setting the scale factor to be much smaller (eg. 1, even though sourmash will squawk at you, it will still work).

I'll turn this into an issue that YACHT should fail more gracefully and descriptively in this situation.
