### ISSUE TITLE
question about yacht for single targets

### ISSUE THREAD

**Issue by AstrobioMike** [KoslickiLab/YACHT#126]
Hiya! 

First, thanks for yacht and the excellent documentation :) 

If interested in asking if just a single target (e.g., a single species or even single genome) is detectable in a sample given whatever thresholds, it is reasonable to sketch and train a reference with just several closely related genomes or even a single genome in there? Or are there key aspects of how yacht works that depend on some broader representation being in the included references?

**Comment by dkoslicki** [comment]
Sorry for the long delay @AstrobioMike , we somehow missed this.

There are no technical barriers to using just a single or few reference genomes, so it's perfectly reasonable to use one or a handful of custom reference genomes. However, you mention "several closely related genomes" which, depending on _how_ closely related, might take some care in some of the settings. For example, if you are using a handful of strains, there might not be many exclusive (distinct to each genome) k-mers at the default k-mer size. You may consider:
1. Increasing the k-mer size (say 31, 41, or 51) which will increase the ability to distinguish closely related strains
2. Increasing the ANI value to ensure that it is bounded away from the maximum pairwise ANI value in your reference (eg. use `sourmash compare --containment --estimate-ani` to compute the pairwise ANI values between your few reference genomes, then ensure that the ANI threshold you select in YACHT is above this to make sure all reference genomes are retained when doing the YACHT training step

Let us know if you encounter any difficulties or unexpected results and we can try to help!

**Comment by AstrobioMike** [comment]
Ah, great, and makes sense! I'll reopen this if I have more questions or if I hit any snags when I get to looking into this. 

Thanks, @dkoslicki!

**Comment by dkoslicki** [comment]
Your response time humiliates ours 😂 !
