### ISSUE TITLE
Expand readme, clarify inputs, etc. (Enhancement)

### ISSUE THREAD

**Issue by gregorysprenger** [KoslickiLab/YACHT#2]
# Current behavior

Commands are listed, no access to path `../ForSteve`, no parameters and information are listed in readme - have to look at the code or download and run the help menu.

# Expected behavior

Have a `Quick start` area with commands and more Indepth information below it. Give link to the `--ref_file` being used in `ref_matrix.py` and use repo path for test data (I should be able to copy your commands and run them on my computer with minimal edits for a "quick start").

Add in a more information on running the scripts and their arguments either in the main readme or another markdown file that is linked in the readme. For instance, do my ref files have to be zip or can they be gzip/some other compression, what is `--w`, what are the acceptable ranges, etc. 

Extra random code update:
Would be nice to update parameters that are one letter to an actual term and the one letter as a short-hand param.. something like: `-w` and `--weight` in the argument parser.

**Comment by dkoslicki** [comment]
Thanks for submitting this issue! You can track the development of a production-level implementation of YACHT [here](https://github.com/orgs/KoslickiLab/projects/2/views/1). Feedback is welcome there too.

**Comment by mfl15** [comment]
PR related to this issue:

PR29: the initial readme, [Shaopeng by ShaopengLiu1 · Pull Request #29 · KoslickiLab/YACHT](https://github.com/KoslickiLab/YACHT/pull/29) 
PR50: one more edit, [Shaopeng by ShaopengLiu1 · Pull Request #50 · KoslickiLab/YACHT](https://github.com/KoslickiLab/YACHT/pull/50)
