### ISSUE TITLE
Dependencies, requirements.txt, and conda (Enhancement)

### ISSUE THREAD

**Issue by gregorysprenger** [KoslickiLab/YACHT#3]
# Current behavior

List the exact version information on dependency tools. When installing `numpy`, it pulls the most updated version. For the off case that an updated version isn't backwards compatible, it would be ideal to know what version of software this tool will work with (kind of the point of conda).

# Expected behavior

1. Version pin software dependencies.
2. Convert requirements.txt to a `yaml` file for conda so that users can just clone the repo, and do `conda env create -f environment.yaml`.

**Comment by dkoslicki** [comment]
Thanks for submitting this issue! You can track the development of a production-level implementation of YACHT [here](https://github.com/orgs/KoslickiLab/projects/2/views/1). Feedback is welcome there too.
