### ISSUE TITLE
Add a warning to users that training step on the entire GTDB will take significant amount of time

### ISSUE THREAD

**Issue by kodh49** [KoslickiLab/YACHT#49]
It will be useful to add a warning to the README file or Wiki that the training step over the entire GTDB will take a significant amount of time and is not expected to run quickly. If users would like to run the algorithm only with a part of the GTDB file, they can use `sourmash sig <argument>` commands to extract signatures of their interest and perform training procedures with this new file.

My local machine only has 8 threads and 16GB memory at maximum to run `sourmash`. In this environment, the following training step with the entire GTDB reference database takes several hours to complete.

`python3 make_training_data_from_sketches.py --ref_file gtdb-rs-214-reps.k21.zip --ksize 21 --num_threads 8 --ani_thresh 0.95 --prefix 'gtdb_ani_thresh_0.95' --outdir ./`

I have been running the procedure with the `gtdb-rs-214-reps.k21.zip` file containing 85205 sketches.

`85205 sketches with DNA, k=21, scaled=1000         270637876 total hashes`

It only has gone to 3% after running for 50 minutes.

**Comment by ShaopengLiu1** [comment]
Added a warning in my branch, please take a look before I merging them @dkoslicki 
https://github.com/KoslickiLab/YACHT/tree/shaopeng#preprocess-the-reference-genomes-training-step

The running time on our GPU server is ~15min for GTDB representative with 16 threads and 50G MEM. But would definitely go to several hours if running with GTDB full data.

**Comment by dkoslicki** [comment]
@ShaopengLiu1 Looks good! Once @kvnthomas98 has the default databases, we can probably conclude with a "We have provided pre-built databases you can download from here..." kinda thing there too

**Comment by ShaopengLiu1** [comment]
Sure, will merge into the main now.
