### ISSUE TITLE
standardize output format

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/YACHT#7]
Currently a lot of things are saved that an end-user won't need. We should:

1. Streamline this by identifying which columns we should keep
2. Provide an option to output results in a standardized format (eg. [biom](https://biom-format.org/) and [CAMI profiling](https://github.com/CAMI-challenge/contest_information/blob/master/file_formats/CAMI_TP_specification.mkd))

**Comment by chunyuma** [comment]
I have[ an existing script](https://github.com/KoslickiLab/YACHT-reproducibles/blob/main/benchmark/scripts/python_scripts/convert_to_CAMI_format_ncbi.py) for this goal. Just need to integrate it into the YACHT production version.

**Comment by chunyuma** [comment]
It is done. So, I close it.
